simulation_metadata:
  device: 'mps'
  num_episodes: 5
  num_steps_per_episode: 5
  num_substeps_per_step: 4

  num_agents: 40
  num_exchanges: 80
  num_assets: 2

  asset_data: 'data/'

state:
    environment:
    agents:
        option_buyer:
            properties:
                starting_capital:
                remaining_capital:
        market_maker:
    objects:
        call_option:
            price:
            strike_price:
            exercise_date:
            time_to_maturity:
            underlying_asset:
        put_option:
            price:
            strike_price:
            exercise_date:
            time_to_maturity:
            underlying_asset:

substeps:
    '0': 
        name: 'buy_option'
    '1':
        name: 'sell_option'
    '2':