simulation_metadata:
  project_name: 'OptionHedgingRL'
  device: 'cpu'
  num_episodes: 10
  num_steps_per_episode: 1000
  seed: 42
  
  # Arbitrary, will need justified change
  
  num_market_makers: 3

  
  num_institutional_investors: 3

  
  num_rl_agents: 1
  

  option_data: 'data/datfile01.xlsx'


state:
 environment:
  market:
   name: 'Market Elements'
   
 agents:
    rl_agent:
      number: ${simulation_metadata.num_rl_agents}
      properties:
        portfolio_value:
          
     
 objects:
 network:
 
substeps:
 '0':
   name:
   description:
   active_agents:
     - 'rl_agent'
 '1':
 '2':
 '3':

